// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzhkodDRQJpw3lx3_fMpN0FyFH-lqHEI',
    appId: '1:134510953526:web:30e399187830b1aa6fc497',
    messagingSenderId: '134510953526',
    projectId: 'coffeeshop-5cfe2',
    authDomain: 'coffeeshop-5cfe2.firebaseapp.com',
    storageBucket: 'coffeeshop-5cfe2.appspot.com',
    measurementId: 'G-FVDJPQTV4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpBBx2iIZ2__E9LyQiXxLLBqDU0UkPa8',
    appId: '1:134510953526:android:4e375270a2ab17fe6fc497',
    messagingSenderId: '134510953526',
    projectId: 'coffeeshop-5cfe2',
    storageBucket: 'coffeeshop-5cfe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJC_da4NT6fzZK43B2P-_F2SLDWooFog',
    appId: '1:134510953526:ios:c9625d1982e85ced6fc497',
    messagingSenderId: '134510953526',
    projectId: 'coffeeshop-5cfe2',
    storageBucket: 'coffeeshop-5cfe2.appspot.com',
    iosClientId: '134510953526-7l6sdumfsr346fmetgus3vtot3gelrh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
